services:
  app:
    image: ubuntu:latest
    command: sh -c "apt update && apt install python3"
    init: true
    volumes:
    - type: bind
      source: /var/run/docker.sock
      target: /var/run/docker.sock
