services:
  app:
    entrypoint:
    - sleep
    - infinity
    image: ubuntu:latest
    command: bash "apt update && apt intall python3 -y"
    init: true
    volumes:
    - type: bind
      source: /var/run/docker.sock
      target: /var/run/docker.sock
