services:
  discordbot:
    build:
      context: .
      dockerfile: Dockerfile
    entrypoint:
    - sleep
    - infinity
    image: alpine
    init: true
    volumes:
    - type: bind
      source: /var/run/docker.sock
      target: /var/run/docker.sock

