version: "3.7"
services:
  discordbot:
    entrypoint:
    - sleep
    - infinity
    image: python:3.12.0
    init: true

volumes:
- type: bind
  source: /var/run/docker.sock
  target: /var/run/docker.sock
  
